apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

patchesJson6902:
- target:
    version: v1
    kind: DeploymentConfig
    name: jupyterhub
    group: apps.openshift.io
  path: jupyterhub-dc.yaml

replicas:
- name: traefik-proxy
  count: 1
